# Generated by Django 4.1.7 on 2023-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_caption_tittle', models.CharField(max_length=30)),
                ('carousel_caption_description', models.CharField(max_length=80)),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
