# Generated by Django 4.1.7 on 2023-03-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_post_delete_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='carousel_caption_description',
            new_name='descripcion_del_curso',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='carousel_caption_tittle',
            new_name='nombre_del_curso',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='numero_del_curso',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
