# Generated by Django 4.1.7 on 2023-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_rename_carousel_caption_description_post_descripcion_del_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_alumno', models.CharField(max_length=20)),
                ('apellido_del_alumno', models.CharField(max_length=20)),
                ('numero_de_alumno', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_profesor', models.CharField(max_length=20)),
                ('apellido_del_profesor', models.CharField(max_length=20)),
                ('numero_de_profesor', models.CharField(max_length=4)),
            ],
        ),
    ]
